# Generated by Django 4.2.5 on 2023-09-12 09:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('header', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_image/')),
                ('info', models.CharField(blank=True, max_length=120, null=True)),
                ('link_text', models.CharField(blank=True, max_length=2000, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
